DefaultContentLanguage = "en"
author = "Sergey Shvyrev"
baseURL = "https://shvyrev.pages.dev/"
copyright = "Copyright © 2008–2024"
disqusShortname = ""
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "" ## or "G-xxxxxxxx" in Google Analytics v4, in hugo v0.82+
hasCJKLanguage = false
languageCode = "en_US"
theme = "hugo-theme-tokiwa"
title = "Sergey Shvyrev"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[params]
bannerFont = "fonts/exampleFont" 
description = """
!!! software development engineer
""" 
env = "production" # for Google Analytics and DISQUS.
favicon = "img/favicon-32x32.png" 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = true # for introducing $KaTeX$
useChineseFonts = false 
postDateFormat = "2006-1-2"

[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "post"
name = "Posts"
url = "/post/"
weight = 1
[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[social]
bilibili = "http://example.com/"
github = "https://github.com/"
gitlab = "https://gitlab.com/"
instagram = "http://example.com/"
mail = "mailto:anon@example.com"
twitter = "https://twitter.com/"
weibo = "http://example.com/"
youtube = "https://youtube.com/"
zhihu = "http://example.com/"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"

[outputs]
home = ["HTML", "RSS", "JSON"]


